# color scheme
# include ./substrata.conf

# Font Size
font_size                          18

# Font Family
font_family                        PT Mono Regular
bold_font                          PT Mono Bold
italic_font                        PT Mono Regular Italic
bold_italic_font                   PT Mono Bold Italic
force_ltr no

# Spacing
adjust_line_height                 5
adjust_column_width                0
adjust_baseline                    0
disable_ligatures                  never

# Cursor
cursor                             #cccccc
cursor_text_color                  background
cursor_shape                       block
cursor_beam_thickness              1.5
cursor_underline_thickness         2.0
cursor_blink_interval              -1
cursor_stop_blinking_after         0

# Bell
enable_audio_bell                  no
