require('options')
require('keymaps')
require('autocmds')
require('pack')

require('core.search')
require('core.statusline')
require('core.lsp')

require('plugins.theme')
require('plugins.dirvish')
require('plugins.quickfix')
require('plugins.treesitter')
require('plugins.surround')
require('plugins.pairs')
require('plugins.ctrlp')
require('plugins.ruby_rails')
require('plugins.vim_test')
require('plugins.tmux')
require('plugins.git')
require('plugins.seeingisbelieving')
require('plugins.peek')
