-- Entry point — loaded when NVIM_APPNAME=nvim-lua (during migration)
-- or when ~/.config/nvim/ points here (post cut-over).

require('options')
require('keymaps')
require('autocmds')
require('pack')

require('plugins.theme')
require('plugins.search')
require('plugins.dirvish')
require('plugins.quickfix')
require('plugins.lualine')
require('plugins.treesitter')
require('plugins.ctrlp')
require('plugins.ruby_rails')
require('plugins.vim_test')
require('plugins.ultisnips')
require('plugins.tmux')
require('plugins.git')
require('plugins.rest')
require('plugins.seeingisbelieving')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.none_ls')
require('plugins.peek')
